---
title: "progress-report-rrrockey"
author: "Ryan Rockey"
date: "2024-04-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(Lahman)
library(dplyr)
library(rvest)
library(readr)

url <- "https://www.baseball-reference.com/awards/hof_2023.shtml"
html <- read_html(url)
tables <- html_table(html)

write.csv(tables[[1]], "temp.csv", row.names = FALSE)
backin <- readr::read_csv("temp.csv", skip = 1, show_col_types = FALSE)


People$fullName <- paste(People$nameFirst, People$nameLast, sep = " ")

# Extract full name from names with various formats
backin$fullName <- backin$Name

# Remove "X-" prefix and " HOF" suffix
backin$fullName <- gsub("^X-|\\s+HOF$", "", backin$fullName)

# Remove extra spaces from "J.J." and "R.A."
People$fullName <- gsub("J. J.", "J.J.", People$fullName)
People$fullName <- gsub("R. A.", "R.A.", People$fullName)

# Replace accented characters
backin$fullName <- gsub("í", "i", backin$fullName)
backin$fullName <- gsub("á", "a", backin$fullName)

backin <- merge(backin, People, by.x = "fullName", by.y = "fullName", all.x = TRUE)

backin$yearID = parse_number(gsub("https://www.baseball-reference.com/awards/hof_", "", url))
backin$votedBy = "BBWAA"
backin$ballots = 389
backin$needed = ceiling(backin$ballots * 0.75)
backin$votes = backin$Votes
backin$inducted = ifelse(backin$votes > backin$needed, "Y", "N")
backin$category = "Player"
backin$needed_note = NA

keep = c("playerID", "yearID", "votedBy", "ballots", "needed", "votes", "inducted", "category", "needed_note")
backin = backin[,(names(backin) %in% keep)]
backin$playerID[28] = "heltoto01"

backin <- backin[order(backin$votes, decreasing = TRUE),]
```



```{r}
new_HallOfFame <- add_row(HallOfFame, backin)

write.csv(new_HallOfFame, "HallOfFame.csv", row.names = FALSE)
```

