---
title: "progress-report-Joshua134512"
output: html_document
date: "2024-04-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(Lahman)
library(rvest)
library(dplyr)
url <- "https://www.baseball-reference.com/awards/hof_2023.shtml"
html <- read_html(url)
tables <- html %>% html_table(fill=TRUE)
write.csv(tables[[1]], "temp.csv", row.names=FALSE)
backin <- readr::read_csv("temp.csv", skip = 1, show_col_types =FALSE)
head(backin, 3)
df <- backin
df$yearID = 2023
df$votedBy = "BBWAA"
df$category = NA
df$needed_note = NA
df$ballots = 389
df$needed=292
df$inducted = ifelse(df$Votes>=292, "Y", "N")
People <- People %>% mutate(
  `Name`=paste(`nameFirst`, `nameLast`)
)
left_join(df, People, by = "Name")

```

```{r}
library(Lahman)
library(ggplot2)
HallOfFame2 <- bind_rows(HallOfFame, df)
HallOfFame2
HallOfFame2 %>% 
  ggplot(aes(x = yearID, fill = inducted)) +
  geom_bar() +
  xlim(c(1936, 2022))
```
